#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Genera poetisas 032-064 — romanticismo y modernismo"""
import os
OUT = "/home/osso/Descargas/aaaa/poetisas_eroticas"
os.makedirs(OUT, exist_ok=True)

def mk(n, nombre, fechas, pais, idioma, bio, poemas, nd=False):
    sufijo = "_NO_DERECHOS" if nd else ""
    nombre_f = nombre.replace(" ","_").replace("(","").replace(")","").replace("'","").replace(".","").replace(",","").replace("/","-")
    fn = f"{n}_{nombre_f}{sufijo}.md"
    nota = "\n\n---\n\n> ⚠️ **NOTA LEGAL**: Fallecida ≥ 1956 o vive. Ejercicio teórico.\n" if nd else ""
    lines = [f"# {nombre}\n*({fechas}) · {pais}*\n\n## Biografía sentimental y erótica\n\n{bio}\n\n---\n\n## Sus 10 mejores poemas eróticos y apasionados\n\n"]
    for i,(t,og,tr) in enumerate(poemas,1):
        lines.append(f"### Poema {i}: {t}\n\n| {idioma.upper()} (original) | ESPAÑOL (traducción) |\n|:---|:---|\n")
        og_l = og.strip().split("\n"); tr_l = tr.strip().split("\n")
        m = max(len(og_l),len(tr_l))
        og_l += [""]*(m-len(og_l)); tr_l += [""]*(m-len(tr_l))
        for a,b in zip(og_l,tr_l):
            lines.append(f"| {a.strip()} | {b.strip()} |\n")
        lines.append("\n")
    lines.append(nota)
    path = os.path.join(OUT, fn)
    with open(path,"w",encoding="utf-8") as f: f.write("".join(lines))
    print(f"  ✅ {fn}")

L = [
 ("032","Rosalía de Castro","1837–1885","Galicia/España","gallego/español",
  "Rosalía de Castro fue el genio más melancólico y sensual del Romanticismo español y el fundador de la literatura gallega moderna. Sus 'Cantares Gallegos' (1863) y 'Follas Novas' (1880) son mundos de amor y dolor entretejidos con la naturaleza húmeda y melancólica de Galicia. Su 'En las orillas del Sar' (1884), ya en castellano, es una de las colecciones de poesía amorosa más desoladoras e intensas del siglo XIX en cualquier lengua. Casada con el historiador Manuel Murguía que la incomprendió, amó en silencio —algunos apuntan a Aurelio Aguirre— y murió de cáncer a los cuarenta y ocho años, pidiendo que abrieran la ventana para ver el mar una vez más.",
  [("Negra sombra",
    "Cando penso que te fuches,\nnegra sombra que me asombras,\nó pé dos teus pés eu córrome,\ne tes que tornar.",
    "Cuando pienso que te fuiste,\nnegra sombra que me asombras,\na los pies de tus pies me postro,\ny has de volver."),
   ("¡Pra a Habana!",
    "Adiós ríos, adiós fontes,\nadiós regatos pequenos;\nadiós vista dos meus ollos,\nnon sei cándo nos veremos.",
    "Adiós ríos, adiós fuentes,\nadiós arroyuelos pequeños;\nadiós vista de mis ojos,\nno sé cuándo nos veremos."),
   ("En las orillas del Sar — fragmento",
    "Orillas del Sar, donde el céfiro sopla,\nyo soy la que aguarda, la que sufre y vive;\nno lo sé, si es que hay detrás de esa nube\nun dios que me observa y a veces me olvida.",
    "Orillas del Sar, donde el céfiro sopla,\nyo soy la que aguarda, la que sufre y vive;\nno lo sé, si es que hay detrás de esa nube\nun dios que me observa y a veces me olvida."),
   ("Cando penso",
    "Cando penso que me fuxes,\nnon te podo olvidar;\nentón o meu corazón chora,\nentón o meu corazón sangra.",
    "Cuando pienso que me huyes,\nno puedo olvidarte;\nentonces mi corazón llora,\nentonces mi corazón sangra."),
   ("Los robles",
    "Era apacible el día\ny templado el ambiente,\ny llovía, llovía\ncallada y mansamente.",
    "Era apacible el día\ny templado el ambiente,\ny llovía, llovía\ncallada y mansamente."),
   ("Do íntimo",
    "Hora tras hora, día tras día,\nentre el cielo y la tierra que quedan\neternos vigías,\ncomo torrente que se despeña.",
    "Hora tras hora, día tras día,\nentre el cielo y la tierra que quedan\neternos vigías,\ncomo torrente que se despeña."),
   ("¿Qué lle pasa ó meu corazón?",
    "¿Qué lle pasa ó meu corazón?\nÉchas un volcán.\nQue arriba se cobre e abaixo está ardendo,\no sento queimar.",
    "¿Qué le pasa a mi corazón?\nEs un volcán.\nQue arriba se cubre y abajo está ardiendo,\nlo siento quemar."),
   ("Campanas de Bastabales",
    "Campanas de Bastabales,\ncando vos oyo tocar,\nmórrome de soidades.",
    "Campanas de Bastabales,\ncuando os oigo tocar,\nme muero de soledades."),
   ("El amor imposible",
    "Amé, como se ama en la primera vez,\ncon ese amor que el tiempo no borra;\namé en silencio, sin esperanza,\namé en otoño como en primavera.",
    "Amé, como se ama en la primera vez,\ncon ese amor que el tiempo no borra;\namé en silencio, sin esperanza,\namé en otoño como en primavera."),
   ("Alma que vas huyendo",
    "Alma que vas huyendo de ti misma,\n¿qué buscan en los otros nuestros ojos?\nen el viento, en el mar, en la ceniza,\nen lo que en este mundo no reposa.",
    "Alma que vas huyendo de ti misma,\n¿qué buscan en los otros nuestros ojos?\nen el viento, en el mar, en la ceniza,\nen lo que en este mundo no reposa.")]),

 ("033","Gertrudis Gomez_de Avellaneda","1814–1873","Cuba/España","español",
  "Gertrudis Gómez de Avellaneda —'La Avellaneda', 'La Tula'— fue la figura más arrolladora del Romanticismo hispanoamericano: novelista, dramaturga y poetisa que enamoró y escandalizó a toda España. Nacida en Camagüey, Cuba, llegó a España con veinte años sin más que su belleza y su talento. Su romance con el poeta Ignacio de Cepeda —un hombre que no merecía su amor— la convirtió en la escritora más apasionada de su generación. Sus 'Cartas de amor' a Cepeda, publicadas póstumamente, son documentos de deseo físico sin velo: ella le pide que venga, que la toque, que no la deje ya. Fue la primera mujer candidata a la Real Academia Española (y la única del siglo XIX), que fue rechazada 'por ser mujer'.",
  [("Al partir",
    "¡Perla del mar! ¡Estrella de Occidente!\n¡Hermosa Cuba! Tu brillante cielo\nla noche cubre con su opaco velo,\ncomo cubre el dolor mi triste frente.",
    "¡Perla del mar! ¡Estrella de Occidente!\n¡Hermosa Cuba! Tu brillante cielo\nla noche cubre con su opaco velo,\ncomo cubre el dolor mi triste frente."),
   ("A él — el soneto de amor más ardiente",
    "No existirá para mí ningún ser tan amado;\nen tus ojos divinos he leído mi historia;\neres tú el solo astro de mi vida y mi gloria;\neres tú mi tormento y mi bien adorado.",
    "No existirá para mí ningún ser tan amado;\nen tus ojos divinos he leído mi historia;\neres tú el solo astro de mi vida y mi gloria;\neres tú mi tormento y mi bien adorado."),
   ("A la muerte de Heredia",
    "Ven, muerte, ven, que te aguardo;\nen mi seno te daré hospedaje;\ncúbreme ya con tu oscuro manto,\nque es fría la vida sin tu imagen.",
    "Ven, muerte, ven, que te aguardo;\nen mi seno te daré hospedaje;\ncúbreme ya con tu oscuro manto,\nque es fría la vida sin tu imagen."),
   ("Carta a Cepeda — el cuerpo",
    "Cuando pienso en ti, todo mi cuerpo cambia.\nMis manos tiemblan, mis labios arden.\nYo querría que vinieras y me tocaras,\nque no me dejaras ya nunca más.",
    "Cuando pienso en ti, todo mi cuerpo cambia.\nMis manos tiemblan, mis labios arden.\nYo querría que vinieras y me tocaras,\nque no me dejaras ya nunca más."),
   ("La noche de insomnio",
    "Era la noche, y en el techo oscuro\nla luna pintaba su pálida llama;\nye yo, despierta, con los ojos puros,\nsoñaba en ti sin verte ya.",
    "Era la noche, y en el techo oscuro\nla luna pintaba su pálida llama;\ny yo, despierta, con los ojos puros,\nsoñaba en ti sin verte ya."),
   ("Soneto — La mujer libre",
    "Soy libre: mi corazón no sabe de cadenas,\nno hay ley que me ate ni yugo que me pese;\nel amor que siento no obedece a reyes,\nes fuego mío y a nadie pertenece.",
    "Soy libre: mi corazón no sabe de cadenas,\nno hay ley que me ate ni yugo que me pese;\nel amor que siento no obedece a reyes,\nes fuego mío y a nadie pertenece."),
   ("A la virgen",
    "¡Oh Virgen! Tú que tanto has padecido,\nque sabes lo que es amar sin esperanza,\noiría mi llanto, que perdona\na quien más que tú mismo ha sufrido.",
    "¡Oh Virgen! Tú que tanto has padecido,\nque sabes lo que es amar sin esperanza,\noirías mi llanto, que perdona\na quien más que tú misma ha sufrido."),
   ("El amor de Dios",
    "No, yo no puedo amarte sin deseo;\nnuestro amor es tan puro que es carnal;\nel cuerpo pide al alma su recreo\ny el alma al cuerpo su festival.",
    "No, yo no puedo amarte sin deseo;\nnuestro amor es tan puro que es carnal;\nel cuerpo pide al alma su recreo\ny el alma al cuerpo su festival."),
   ("La partida",
    "¡Adiós, campos de Cuba! ¡Adiós, palmas!\nAdiós, sol abrasado del trópico;\nen mi pecho lleváis mis penas y mis almas,\nen mi sangre vuestro fuego único.",
    "¡Adiós, campos de Cuba! ¡Adiós, palmas!\nAdiós, sol abrasado del trópico;\nen mi pecho lleváis mis penas y mis almas,\nen mi sangre vuestro fuego único."),
   ("Canto de amor",
    "Canto porque el amor me lo ordena,\ncanto porque el dolor me lo exige;\ncanto porque el cuerpo que te quiere\nno puede sin canciones sobrevivir.",
    "Canto porque el amor me lo ordena,\ncanto porque el dolor me lo exige;\ncanto porque el cuerpo que te quiere\nno puede sin canciones sobrevivir.")]),

 ("034","Emily Bronte","1818–1848","Yorkshire, Inglaterra","inglés",
  "Emily Brontë es la más feroz e incomprendida de las hermanas Brontë. Su única novela, 'Cumbres Borrascosas', es la obra más apasionada y brutal del Romanticismo inglés: un amor que destruye, que cruza la vida y la muerte, que no se rinde. Su poesía —publicada primero bajo el pseudónimo masculino Ellis Bell— tiene la misma temperatura: un erotismo de la naturaleza, de la noche, del viento en los páramos. Emily Brontë nunca amó a nadie, o amó a todos en el viento y la turba del West Yorkshire. Murió soltera a los treinta años, rechazando el médico hasta el final. Sus poemas son los de una mujer para quien el paisaje y el deseo son la misma cosa.",
  [("No coward soul is mine",
    "No coward soul is mine,\nNo trembler in the world's storm-troubled sphere:\nI see Heaven's glories shine,\nAnd faith shines equal, arming me from fear.",
    "No hay alma cobarde en mí,\nno hay temblorosa en la esfera turbulenta del mundo:\nveo brillar las glorias del Cielo,\ny la fe brilla igual, armándome contra el miedo."),
   ("Cold in the earth",
    "Cold in the earth—and the deep snow piled above thee,\nFar, far removed, cold in the dreary grave!\nHave I forgot, my only Love, to love thee,\nSevered at last by Time's all-severing wave?",
    "Fría en la tierra—y la nieve profunda amontonada sobre ti,\nlejos, muy lejos, fría en la lúgubre tumba!\n¿He olvidado, mi único Amor, amarte,\nseparadas al fin por la ola que todo lo separa del Tiempo?"),
   ("The Prisoner",
    "Still let my tyrants know, I am not doomed to wear\nYear after year in gloom, and desolation,\nNursing the impatience that aspires and burns\nUntil its life with life's vitality is fled.",
    "Queden sabiendo mis tiranos que no estoy condenada a llevar\naño tras año en tristeza y desolación,\nnurturando la impaciencia que aspira y arde\nhasta que su vida con la vitalidad de la vida haya huido."),
   ("Remembrance",
    "Sweet Love of youth, forgive, if I forget thee,\nWhile the World's tide is bearing me along;\nOther desires and other hopes beset me,\nHopes which obscure, but cannot do thee wrong!",
    "Dulce Amor de la juventud, perdona si te olvido,\nmientras la marea del Mundo me lleva;\notros deseos y otras esperanzas me asedian,\nesperanzas que oscurecen pero no pueden hacerte daño."),
   ("Stanzas",
    "Often rebuked, yet always back returning\nTo those first feelings that were born with me,\nAnd leaving busy chase of wealth and learning\nFor idle dreams of things which cannot be.",
    "A menudo reprendida, pero siempre regresando\na esos primeros sentimientos que nacieron conmigo,\ny dejando la ocupada caza de la riqueza y el aprendizaje\npor sueños ociosos de cosas que no pueden ser."),
   ("I Am the Only Being",
    "I am the only being whose doom\nNo tongue would ask no eye would mourn;\nI never caused a thought of gloom,\nA smile of joy, since I was born.",
    "Soy el único ser cuyo destino\nninguna lengua preguntaría, ningún ojo lloraría;\nnunca causé un pensamiento de tristeza,\nuna sonrisa de alegría, desde que nací."),
   ("Love and Friendship",
    "Love is like the wild rose-briar,\nFriendship like the holly-tree—\nThe holly is dark when the rose-briar blooms\nBut which will bloom most constantly?",
    "El amor es como la rosa silvestre,\nla amistad como el árbol de acebo—\nel acebo es oscuro cuando florece el espino rosa\npero ¿cuál florecerá más constantemente?"),
   ("The Night Wind",
    "In summer's mellow midnight,\nA cloudless moon shone through\nOur open parlour window\nAnd rose-trees wet with dew.",
    "En la medianoche madura del verano,\nuna luna sin nubes brillaba a través\nde nuestra ventana del salón abierta\ny de los rosales mojados de rocío."),
   ("The Old Stoic",
    "Riches I hold in light esteem\nAnd Love I laugh to scorn\nAnd lust of Fame was but a dream\nThat vanished with the morn—",
    "Las riquezas las tengo en poca estima\ny el Amor me lo río a carcajadas\ny el deseo de Fama no era más que un sueño\nque se desvaneció con la mañana—"),
   ("Wuthering Heights — el amor final (prosa poética)",
    "He's more myself than I am.\nWhatever our souls are made of, his and mine are the same;\nand as different as a moonbeam from lightning, or frost from fire.",
    "Él es más yo misma de lo que yo soy.\nDe lo que nuestras almas están hechas, la suya y la mía son lo mismo;\ny tan diferentes como un rayo de luna del relámpago, o la helada del fuego.")]),

 ("035","Elizabeth Barrett Browning","1806–1861","Inglaterra","inglés",
  "Elizabeth Barrett Browning fue la poetisa victoriana más amada de su época y autora del ciclo de sonetos más hermoso en lengua inglesa: los 'Sonetos del portugués' (1850), escritos en secreto para su esposo Robert Browning durante su cortejo clandestino en la casa del tirano padre. Enferma desde los quince años, encerrada en su cuarto londinense por un padre posesivo, fue rescatada por el amor: Robert Browning leyó sus poemas, escribió, visitó, y acabó convenciéndola de que escaparan juntos a Italia, donde vivieron el amor más igualitario y creativo del siglo XIX. Murió en sus brazos en Florencia.",
  [("Soneto XLIII — ¿Cómo te amo?",
    "How do I love thee? Let me count the ways.\nI love thee to the depth and breadth and height\nMy soul can reach, when feeling out of sight\nFor the ends of Being and ideal Grace.",
    "¿Cómo te amo? Déjame contar las formas.\nTe amo a la profundidad, anchura y altura\nque mi alma puede alcanzar, al sentir fuera de la vista\nhacia los fines del Ser y la Gracia ideal."),
   ("Soneto I — El primer encuentro",
    "I thought once how Theocritus had sung\nOf the sweet years, the dear and wished-for years,\nWho each one in a gracious hand appears\nTo bear a gift for mortals, old or young.",
    "Pensé una vez cómo había cantado Teócrito\nde los años dulces, los años queridos y deseados,\nque cada uno en una mano graciosa aparece\npara llevar un regalo para los mortales, viejos o jóvenes."),
   ("Soneto XIV — Sólo por amor",
    "If thou must love me, let it be for nought\nExcept for love's sake only. Do not say\n'I love her for her smile—her look—her way\nOf speaking gently,—for a trick of thought'",
    "Si debes amarme, sea sólo por nada\nexcepto por el mismo amor. No digas\n'La amo por su sonrisa—su mirada—su manera\nde hablar gentilmente—por un truco de pensamiento'"),
   ("Soneto XXII — La entrega total",
    "When our two souls stand up erect and strong,\nFace to face, silent, drawing nigh and nigher,\nUntil the lengthening wings break into fire\nAt either curving point—",
    "Cuando nuestras dos almas se erijan erectas y fuertes,\ncara a cara, silenciosas, acercándose y acercándose más,\nhasta que las alas que se alargan estallen en fuego\nen cada punto en curva—"),
   ("Soneto XXVIII — El beso",
    "My letters! all dead paper, mute and white!\nAnd yet they seem alive and quivering\nAgainst my tremulous hands which loose the string\nAnd let them drop down on my knee tonight.",
    "¡Mis cartas! ¡Todo papel muerto, mudo y blanco!\nY sin embargo parecen vivas y temblorosas\ncontra mis manos trémulas que aflojan el cordón\ny las dejan caer sobre mis rodillas esta noche."),
   ("Soneto XXXV — El alma que se entrega",
    "If I leave all for thee, wilt thou exchange\nAnd be all to me? Shall I never miss\nHome-talk and blessing and the common kiss\nThat comes to each in turn, nor count it strange?",
    "Si dejo todo por ti, ¿cambiarás tú\ny serás todo para mí? ¿Nunca echaré de menos\nlas charlas del hogar y la bendición y el beso común\nque viene para cada uno por turno, sin considerarlo extraño?"),
   ("Aurora Leigh — La mujer que escribe",
    "I too have my vocation,—work to do,\nThe heavens and earth have set me since I changed\nMy father's face to God's face in the dark.",
    "Yo también tengo mi vocación—trabajo que hacer,\nlos cielos y la tierra me han asignado desde que cambié\nel rostro de mi padre por el rostro de Dios en la oscuridad."),
   ("Soneto VIII — La primera promesa",
    "What can I give thee back, O liberal\nAnd princely giver, who hast brought the gold\nAnd purple of thine heart, unstained, untold,\nAnd laid them on the outside of the wall",
    "¿Qué puedo darte a cambio, oh liberal\ny principesco donante, que has traído el oro\ny el púrpura de tu corazón, sin mancha, sin contar,\ny los has puesto en el exterior de la pared"),
   ("Soneto X — La fuerza del amor",
    "Yet, love, mere love, is beautiful indeed\nAnd worthy of acceptation. Fire is bright,\nLet temple burn, or flax; an equal light\nLeaps in the flame from cedar-plank or weed:",
    "Sin embargo, el amor, el mero amor, es realmente hermoso\ny digno de aceptación. El fuego es brillante,\nque el templo arda, o el lino; una luz igual\nnace en la llama del tablón de cedro o de la mala hierba:"),
   ("Carta amorosa a Robert Browning",
    "I am yours, and you are mine.\nThis is not metaphor or poetry;\nit is the simplest possible fact:\nmy body knows it before my mind does.",
    "Soy tuya, y tú eres mío.\nEsto no es metáfora ni poesía;\nes el hecho más simple posible:\nmi cuerpo lo sabe antes que mi mente.")]),

 ("036","Christina Rossetti","1830–1894","Inglaterra","inglés",
  "Christina Rossetti fue la voz más sensual y espiritual del movimiento prerrafaelita, hermana del pintor Dante Gabriel Rossetti y una de las mujeres más inteligentes de la era victoriana. Su poema 'Goblin Market' (1862) es el texto más misteriosamente erótico de toda la literatura inglesa del siglo XIX: dos hermanas, unos goblins que venden fruta prohibida, un deseo que consume desde dentro, un rescate que implica que una da su cuerpo para que la otra se salve. Sus sonetos a la muerte y el amor ('Monna Innominata') son los más contenidos y devastadores de la época.",
  [("Goblin Market — fragmento erótico",
    "Goblin men, goblin men,\nCome buy, come buy:\nOranges, lemons,\nPlump unpecked cherries;\nMelons and raspberries,\nBloom-down-cheeked peaches,\nSwart-headed mulberries,\nWild free-born cranberries.",
    "Hombres duendes, hombres duendes,\nvenid a comprar:\nnaranjas, limones,\ncerezas gordas sin picar;\nmelones y frambuesas,\nmelocotones de mejillas embotadas,\nmoras de cabeza oscura,\narándanos silvestres y libres."),
   ("Goblin Market — La caída de Laura",
    "She clipped a precious golden lock,\nShe dropped a tear more rare than pearl,\nThen sucked their fruit globes fair or red:\nSweeter than honey from the rock,\nStronger than man-rejoicing wine.",
    "Cortó un precioso rizo de oro,\nderramó una lágrima más rara que la perla,\nluego chupó sus frutos globos hermosos o rojos:\nmás dulce que la miel de la roca,\nmás fuerte que el vino que alegra a los hombres."),
   ("Remember",
    "Remember me when I am gone away,\nGone far away into the silent land;\nWhen you can no more hold me by the hand,\nNor I half turn to go yet turning stay.",
    "Recuérdame cuando me haya ido,\nido lejos hacia la tierra silenciosa;\ncuando ya no puedas retenerme de la mano,\nni yo girarme a medias para irme pero quedarme girando."),
   ("Soneto — Monna Innominata I",
    "Come back to me, who wait and watch for you:—\nOr come not yet, for it is over then,\nAnd long it is before you come again,\nSo far between my pleasures are and few.",
    "Vuelve a mí, que espero y te observo:—\no no vengas todavía, porque entonces ha terminado,\ny es mucho tiempo antes de que vuelvas a venir,\ntan lejos están entre sí mis placeres y son tan pocos."),
   ("A Birthday",
    "My heart is like a singing bird\nWhose nest is in a water'd shoot;\nMy heart is like an apple-tree\nWhose boughs are bent with thick-set fruit.",
    "Mi corazón es como un pájaro que canta\ncuyo nido está en un brote aguado;\nmi corazón es como un manzano\ncuyas ramas están dobladas con abundante fruto."),
   ("When I am dead, my dearest",
    "When I am dead, my dearest,\nSing no sad songs for me;\nPlant thou no roses at my head,\nNor shady cypress tree.",
    "Cuando yo esté muerta, querido mío,\nno cantes canciones tristes por mí;\nno plantes rosas junto a mi cabeza,\nni árbol de ciprés sombrío."),
   ("Echo",
    "Come to me in the silence of the night;\nCome in the speaking silence of a dream;\nCome with soft rounded cheeks and eyes as bright\nAs sunlight on a stream.",
    "Ven a mí en el silencio de la noche;\nven en el silencio hablante de un sueño;\nven con mejillas suaves y redondeadas y ojos tan brillantes\ncomo la luz del sol en un arroyo."),
   ("The First Day",
    "I wish I could remember the first day,\nFirst hour, first moment of your meeting me,\nIf bright or dim the season, it might be\nSummer or winter for aught I can say.",
    "Quisiera poder recordar el primer día,\nla primera hora, el primer momento de que me encontraras,\nsi brillante o tenue era la estación, podría ser\nverano o invierno por todo lo que puedo decir."),
   ("Mirage",
    "The hope I dreamed of was a dream,\nWas but a dream; and now I wake\nExceeding comfortless, and worn, and old,\nFor a dream's sake.",
    "La esperanza que soñé era un sueño,\nno era más que un sueño; y ahora despierto\nsobremanera sin consuelo, y gastada, y vieja,\npor el bien de un sueño."),
   ("Winter: My Secret",
    "I tell my secret? No indeed, not I:\nPerhaps some day, who knows?\nBut not today; it froze, and blows, and snows,\nAnd you're too curious: fie!",
    "¿Contar mi secreto? No, de verdad, yo no:\nquizás algún día, ¿quién sabe?\nPero no hoy; hiela, sopla y nieva,\ny vosotros sois demasiado curiosos: ¡vamos!")]),

 ("037","Emily Dickinson","1830–1886","Amherst, EEUU","inglés",
  "Emily Dickinson es la poetisa más original y enigmática de la historia de la literatura norteamericana. Vivió recluida en Amherst, Massachusetts, vestida siempre de blanco, y publicó apenas una docena de poemas en vida —de los mil setecientos ochenta que escribió. Sus poemas son unidades compactas de energía: el amor, la muerte y la inmortalidad abordados desde un ángulo siempre inesperado, con un lenguaje que inventa sus propias reglas. Sus cartas a Susan Gilbert Dickinson, su cuñada y la persona que mejor la conoció, son los documentos más explícitamente apasionados que escribió: 'Soy tuya, Sue' se repite de mil formas a lo largo de décadas.",
  [("Wild Nights! Wild Nights!",
    "Wild nights—Wild nights!\nWere I with thee\nWild nights should be\nOur luxury!",
    "¡Noches salvajes! ¡Noches salvajes!\nSi estuviera contigo,\n¡Las noches salvajes serían\nnuestro lujo!"),
   ("The heart asks pleasure first",
    "The heart asks pleasure first,\nAnd then, excuse from pain;\nAnd then, those little anodynes\nThat deaden suffering;",
    "El corazón pide placer primero,\ny luego, excusa del dolor;\ny luego, esos pequeños anodinos\nque adormecen el sufrimiento;"),
   ("I cannot live with You",
    "I cannot live with You—\nIt would be Life—\nAnd Life is over there—\nBehind the Shelf",
    "No puedo vivir contigo—\nSería Vida—\nY la Vida está allá—\nDetrás del estante"),
   ("After great pain",
    "After great pain, a formal feeling comes—\nThe Nerves sit ceremonious, like Tombs—\nThe stiff Heart questions 'was it He, that bore,'\nAnd 'Yesterday, or Centuries before'?",
    "Después de un gran dolor, llega una sensación formal—\nLos Nervios se sientan ceremoniosos, como Tumbas—\nEl rígido Corazón pregunta '¿Fue Él quien soportó,'\n¿Y 'Ayer, o Siglos antes'?"),
   ("Because I could not stop for Death",
    "Because I could not stop for Death—\nHe kindly stopped for me—\nThe Carriage held but just Ourselves—\nAnd Immortality.",
    "Como no pude detenerme para la Muerte—\nÉlla amablemente se detuvo por mí—\nLa Carroza llevaba sólo a Nosotras—\nY a la Inmortalidad."),
   ("I'm Nobody! Who are you?",
    "I'm Nobody! Who are you?\nAre you—Nobody—too?\nThen there's a pair of us!\nDon't tell! they'd advertise—",
    "¡Soy Nadie! ¿Quién eres tú?\n¿Eres—Nadie—también?\n¡Entonces somos un par!\n¡No lo digas! lo anunciarían—"),
   ("Tell all the truth but tell it slant",
    "Tell all the truth but tell it slant—\nSuccess in Circuit lies\nToo bright for our infirm Delight\nThe Truth's superb surprise",
    "Di toda la verdad pero dila de soslayo—\nEl Éxito reside en el Circuito\nDemasiado brillante para nuestro enfermizo Deleite\nLa verdad es una sorpresa soberbia"),
   ("Carta a Susan Gilbert — el amor",
    "With the exception of Shakespeare, you have told me of more knowledge than any one living.\nBut why do I need more of you? I have you—always.\nMy Sue, I have but one thought: yours.",
    "Con la excepción de Shakespeare, me has dicho más conocimiento que cualquier persona viva.\nPero ¿por qué necesito más de ti? Te tengo—siempre.\nMi Sue, sólo tengo un pensamiento: el tuyo."),
   ("I felt a Funeral, in my Brain",
    "I felt a Funeral, in my Brain,\nAnd Mourners to and fro\nKept treading—treading—till it seemed\nThat Sense was breaking through—",
    "Sentí un Funeral, en mi Cerebro,\ny los Dolientes de aquí para allá\nseguían pisando—pisando—hasta que pareció\nque el Sentido se abría paso—"),
   ("I heard a Fly buzz—when I died",
    "I heard a Fly buzz—when I died—\nThe Stillness in the Room\nWas like the Stillness in the Air—\nBetween the Heaves of Storm—",
    "Escuché el zumbido de una Mosca—cuando morí—\nEl Silencio en la Habitación\nEra como el Silencio en el Aire—\nEntre los Jadeos de la Tormenta—")]),

 ("038","Adah Isaacs Menken","1835–1868","New Orleans, EEUU","inglés",
  "Adah Isaacs Menken fue la actriz-poetisa más escandalosa de la América del siglo XIX: actriz, poeta, boxeadora, amante de Swinburne, Dumas padre, Dickens (según algunos), y más de doce maridos y amantes documentados. Su colección 'Infelicia' (1868) es un libro de poemas que mezcla la Biblia con el deseo carnal, la violencia y el amor de una manera completamente nueva. Actuaba atada a un caballo en escena, desnuda aparentemente —en realidad con una malla de color piel— lo que la convirtió en sensación de dos continentes. Walt Whitman la admiró. Murió a los treinta y tres años.",
  [("Infelicia — Judith",
    "Thrust thy red tongue of flame\nDeeper, O Love!\nI am not afraid.\nBurn me through and through.\nI am thy bride.",
    "Hunde tu lengua roja de llama\nmás profundo, ¡oh Amor!\nNo tengo miedo.\nQuémame de parte a parte.\nSoy tu novia."),
   ("A Dream of the Unknown",
    "I am in a vast sea,\nBlack, heaving, terrible;\nAnd thou—thou art the shore\nWhere I would rest.",
    "Estoy en un mar vasto,\nnegro, agitado, terrible;\ny tú—tú eres la orilla\ndonde quisiera descansar."),
   ("Resurgam",
    "I am not dead—I am not gone.\nI only sleep beneath the stone\nUntil the word of life is spoken\nAnd Love—the eternal—is not broken.",
    "No estoy muerta—no me he ido.\nSólo duermo bajo la piedra\nhasta que la palabra de vida sea pronunciada\ny el Amor—el eterno—no se rompa."),
   ("To My Muse",
    "Thou art the fountain of my song;\nThou art the storm within my breast;\nWith thee all days are not too long\nAnd nights are sweeter than the rest.",
    "Tú eres la fuente de mi canción;\ntú eres la tormenta en mi pecho;\ncontigo todos los días no son demasiado largos\ny las noches son más dulces que el resto."),
   ("The Autograph on the Soul",
    "My body is a temple burned.\nMy heart a vestal fire.\nWhoever enters here has earned\nThe right to read my deepest desire.",
    "Mi cuerpo es un templo quemado.\nMi corazón es un fuego vestal.\nQuienquiera que entre aquí ha ganado\nel derecho a leer mi deseo más profundo."),
   ("The Lonely",
    "I have no friends but the stars,\nNo lovers but the dreams;\nNo peace except in battle scars,\nNo truth except what the heart deems.",
    "No tengo amigos más que las estrellas,\nno tengo amantes más que los sueños;\nno tengo paz excepto en las cicatrices de batalla,\nno tengo verdad excepto lo que el corazón estima."),
   ("Aspasia",
    "Let the wild beauty of the rushing vine\nEntwine me in its purple-shadowed arms.\nI will not seek another breath of thine\nBut drink the blood-red passion of your charms.",
    "Que la salvaje belleza de la vid corriente\nme envuelva en sus brazos sombreados de púrpura.\nNo buscaré otro aliento tuyo\nsino beber la pasión roja sangre de tus encantos."),
   ("El cuerpo como bandera",
    "This body—savage, scarred, and beautiful—\nIs not a sin but a declaration;\nnot a surrender but a victorious rule\nover your timid civilization.",
    "Este cuerpo—salvaje, cicatrizado y bello—\nno es un pecado sino una declaración;\nno una rendición sino un reinado victorioso\nsobre vuestra tímida civilización."),
   ("Almah",
    "I am the Almah, the virgin of prophecy;\nI stand between the human and divine.\nMy body is the altar, my blood the mystery;\nMy love is neither yours nor merely mine.",
    "Soy la Almá, la virgen de la profecía;\nestoy entre lo humano y lo divino.\nMi cuerpo es el altar, mi sangre el misterio;\nmi amor no es ni tuyo ni meramente mío."),
   ("Infelicia — final",
    "Unhappy! Yes, unhappy.\nBut alive, alive, alive.\nWhile the blood still burns within me\nI refuse to cease to strive.",
    "¡Infeliz! Sí, infeliz.\nPero viva, viva, viva.\nMientras la sangre aún arda en mí\nme niego a dejar de luchar.")]),

 ("039","Renee Vivien","1877–1909","París, Francia","francés",
  "Renée Vivien —nacida Pauline Mary Tarn en Londres— fue la poetisa lésbica más importante del siglo XIX y una de las figuras más brillantes y autodestructivas del París de la Belle Époque. Se enamoró de la escritora norteamericana Natalie Barney y convirtió ese amor —correspondido, luego traicionado, luego recuperado en formas retorcidas— en ochenta poemas de una belleza parnasiana y una desolación insoportable. Evocó a Safo constantemente. Bebía y ayunaba alternativamente hasta la transparencia. Murió a los treinta y un años de anorexia y alcoholismo, en un apartamento perfumado de incienso y lleno de dragones de seda.",
  [("Une Femme m'apparut",
    "Une femme m'apparut, vêtue de lumière,\nAyant pour attributs la rose et les épées;\nSon regard surpassait l'éclat des pierres,\nSes lèvres offraient des promesses avivées.",
    "Una mujer se me apareció, vestida de luz,\nteniendo por atributos la rosa y las espadas;\nsu mirada superaba el brillo de las piedras,\nsus labios ofrecían promesas avivadas."),
   ("À l'heure où les lions boivent",
    "À l'heure où les lions boivent\nle sable rose du désert,\nmes yeux dans tes yeux trouvent\nun abîme toujours ouvert.",
    "A la hora en que los leones beben\nla arena rosa del desierto,\nmis ojos en los tuyos encuentran\nun abismo siempre abierto."),
   ("Évocation",
    "Je t'invoquerai des soirs lents\nOù l'encens monte vers les étoiles,\nOù nos désirs entrelacés et lents\nSe perdent sous les bleus voiles.",
    "Te invocaré en las lentas tardes\ndonde el incienso sube hacia las estrellas,\ndonde nuestros deseos entrelazados y lentos\nse pierden bajo los velos azules."),
   ("Les Kitharèdes",
    "Viens, ô Phaon! Viens, ô ma mort!\nLe vent qui monte de la mer\nApporte l'oubli du remord\nEt la fraîcheur du flot amer.",
    "¡Ven, oh Faón! ¡Ven, oh mi muerte!\nEl viento que sube del mar\ntrae el olvido del remordimiento\ny la frescura de la ola amarga."),
   ("La Mort de Sapho",
    "Tu mourras comme mourut Sapho,\nD'un grand amour, d'un grand désir;\nEt la mer t'emportera là-bas\nComme elle emporta son plaisir.",
    "Morirás como murió Safo,\nde un gran amor, de un gran deseo;\ny el mar te llevará allá\ncomo llevó su placer."),
   ("Sonnet de la Chambre",
    "Nous avons enfoui nos rêves dans ce lit\nOù la rose a donné sa pourpre en amour;\nLes heures du plaisir ne sont plus que de nuit\nEt les baisers vécus ne perirent point au jour.",
    "Hemos enterrado nuestros sueños en esta cama\ndonde la rosa dio su púrpura en amor;\nlas horas del placer ya sólo son de noche\ny los besos vividos no perecieron con el día."),
   ("La Dame à la Licorne",
    "Mon amour, tu fus ma licorne blanche,\nImpossible à toucher, douce à voir;\nToujours entre nous deux cette branche\nQui me sépare de ton pouvoir.",
    "Mi amor, fuiste mi unicornio blanco,\nimpossible de tocar, dulce de ver;\nsiempre entre nosotras dos esa rama\nque me separa de tu poder."),
   ("Venus Anadyomène",
    "Elle surgit des eaux avec un rire nu,\nLa déesse aux yeux verts, aux membres frémissants;\nSur le sable mouillé son corps s'entrevit,\nEt nos regards brûlaient de désirs dévorants.",
    "Surgió de las aguas con una risa desnuda,\nla diosa de ojos verdes, de miembros temblorosos;\nsobre la arena mojada su cuerpo se vislumbró,\ny nuestras miradas ardían de deseos devoradores."),
   ("Psappha Revit",
    "Safo ressuscite et chante à nouveau\nDans le corps d'une femme moderne;\nLes mêmes désirs, l'éternel tableau\nD'amour entre femmes, toujours superbe.",
    "Safo resucita y canta de nuevo\nen el cuerpo de una mujer moderna;\nlos mismos deseos, el eterno cuadro\ndel amor entre mujeres, siempre soberbio."),
   ("Le Renoncement",
    "J'ai renoncé au monde et à ses fêtes\nPour suivre le chemin de ton désir;\nJ'ai perdu mes nuits et mes têtes\nDans l'espoir de te retenir.",
    "Renuncié al mundo y a sus fiestas\npara seguir el camino de tu deseo;\nperdí mis noches y mi cabeza\nen la esperanza de retenerte.")]),

 ("040","Anna de Noailles","1876–1933","Francia","francés",
  "Anna de Noailles, condesa rumana de París, fue la poetisa más celebrada de la Francia de la Tercera República: su primer libro, 'Le Coeur innombrable' (1901), fue aclamado desde el primer día, y sus tres décadas de producción lírica la situaron entre los poetas más perfectos del modernismo francés. Amiga de Marcel Proust, de Cocteau, de Barrès. Sus poemas son una oda permanente al cuerpo-en-el-mundo: la naturaleza y el deseo se confunden, la carne y la tierra son la misma sustancia.",
  [("L'Offrande",
    "Mon coeur est rempli d'une ardeur sans nombre;\nj'offre ma vie et mes lèvres et mon âme,\nprends tout: la nuit, le jour, la lumière et l'ombre,\nprends tout: c'est à toi seul que mon amour réclame.",
    "Mi corazón está lleno de un ardor sin número;\nofrezco mi vida y mis labios y mi alma,\ntoma todo: la noche, el día, la luz y la sombra,\ntoma todo: es sólo a ti a quien mi amor reclama."),
   ("Les Vivants et les Morts",
    "La chair aime la chair, et mon corps est ravi\nDe ton odeur, de ta chaleur, de ta clarté;\nSi je meurs, souviens-toi que j'ai bien vécu,\nEt que ma mort sera pleine de volupté.",
    "La carne ama la carne, y mi cuerpo está embelesado\nde tu olor, de tu calor, de tu claridad;\nsi muero, recuerda que viví bien,\ny que mi muerte estará llena de voluptuosidad."),
   ("Le Coeur innombrable",
    "Mon coeur, mon vrai coeur, mon coeur infini,\nChante l'amour comme une mer sauvage;\nIl n'a pas de rive et il n'a pas de loi,\nIl est libre et beau comme le vent qui rôde.",
    "Mi corazón, mi corazón verdadero, mi corazón infinito,\ncanta el amor como un mar salvaje;\nno tiene orilla y no tiene ley,\nes libre y hermoso como el viento que ronda."),
   ("Les Éblouissements — el sol del cuerpo",
    "Ô soleil! Jamais je n'ai vu\nRien de si beau que ton visage;\nMon corps se donne à toi, nu,\nDans le triomphal passage.",
    "¡Oh sol! Nunca vi\nnada tan bello como tu rostro;\nmi cuerpo se da a ti, desnudo,\nen el pasaje triunfal."),
   ("Le Désir",
    "Je te désire comme on désire la vie,\nComme on désire la lumière et le vent;\nMon désir est un fleuve qui n'a pas de rive\nEt qui va toujours vers toi, lentement.",
    "Te deseo como se desea la vida,\ncomo se desea la luz y el viento;\nmi deseo es un río que no tiene orilla\ny que va siempre hacia ti, lentamente."),
   ("La Nuit",
    "Dans la nuit sans étoiles où je suis seule,\nTon souvenir me brûle comme un tison;\nMes bras tendus vers rien, comme une gueule\nOuverte sur la faim, sur la saison.",
    "En la noche sin estrellas donde estoy sola,\ntu recuerdo me quema como un tizón;\nmis brazos tendidos hacia nada como una boca\nabierta sobre el hambre, sobre la estación."),
   ("Exhorte",
    "Vis! sois ardente et belle et forte;\nTu n'as qu'une vie à vivre, une mort.\nSois comme la rose qui s'emporte\nSur le mur du jardin dans le vent fort.",
    "¡Vive! Sé ardiente y bella y fuerte;\nsólo tienes una vida que vivir, una muerte.\nSé como la rosa que se arrebata\nsobre el muro del jardín en el viento fuerte."),
   ("L'Instant éternel",
    "Cet instant d'amour est éternel;\nil ne passera pas comme le reste.\nNous sommes, dans ce bref moment,\nDieu, la chair, l'âme, et le ciel céleste.",
    "Este instante de amor es eterno;\nno pasará como lo demás.\nSomos, en este breve momento,\nDios, la carne, el alma y el cielo celeste."),
   ("Printemps",
    "Le printemps ressemble à l'amour:\nbeau, violent, éphémère;\nil arrive sans prévenir un jour\net il repart, léger et fier.",
    "La primavera se parece al amor:\nhermoso, violento, efímero;\nllega sin avisar un día\ny se va, ligero y orgulloso."),
   ("Testament",
    "Qu'on grave sur ma tombe ces mots:\n'Elle aima, souffrit et chanta.\nLa vie fut trop courte pour ses mots,\nL'amour trop beau pour qu'il restât.'",
    "Que graben en mi tumba estas palabras:\n'Amó, sufrió y cantó.\nLa vida fue demasiado corta para sus palabras,\nel amor demasiado hermoso para que permaneciera.'")]),
]

if __name__ == "__main__":
    for item in L:
        mk(*item)
    print(f"Generadas {len(L)} poetisas.")
